export const InvoiceError = {
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  INVOICE_NOT_ELIGIBLE: "INVOICE_NOT_ELIGIBLE",
  INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
  TAX_ID_INCOMPLETE: "TAX_ID_INCOMPLETE",
  STORE_SETTINGS_MISSING: "STORE_SETTINGS_MISSING",
} as const;

export type InvoiceErrorCode = (typeof InvoiceError)[keyof typeof InvoiceError];
